"""macOS LaunchAgent 排程產生器。

產生 shell 腳本 + launchd .plist，對應 windows_task.py 的功能。
"""

from __future__ import annotations

import stat
import sys
from pathlib import Path

from src.config import PROJECT_ROOT


def generate_scripts() -> tuple[Path, Path]:
    """產生每日 .sh 腳本 + LaunchAgent plist，回傳 (sh_path, plist_path)。"""
    script_dir = PROJECT_ROOT / "scripts"
    script_dir.mkdir(exist_ok=True)
    log_dir = PROJECT_ROOT / "logs"
    log_dir.mkdir(exist_ok=True)

    sh_path = script_dir / "daily_sync.sh"
    plist_path = script_dir / "com.taiwan-quant.daily-sync.plist"

    _generate_shell(sh_path, log_dir)
    _generate_plist(plist_path, sh_path)
    _print_instructions(sh_path, plist_path, log_dir)

    return sh_path, plist_path


def generate_weekly_scripts() -> tuple[Path, Path]:
    """產生每週四 sync-holding .sh + LaunchAgent plist，回傳 (sh_path, plist_path)。"""
    script_dir = PROJECT_ROOT / "scripts"
    script_dir.mkdir(exist_ok=True)
    log_dir = PROJECT_ROOT / "logs"
    log_dir.mkdir(exist_ok=True)

    sh_path = script_dir / "weekly_sync.sh"
    plist_path = script_dir / "com.taiwan-quant.weekly-holding.plist"

    _generate_weekly_shell(sh_path, log_dir)
    _generate_weekly_plist(plist_path, sh_path)
    _print_weekly_instructions(sh_path, plist_path, log_dir)

    return sh_path, plist_path


def _generate_shell(output: Path, log_dir: Path) -> None:
    """產生每日 morning-routine shell 腳本。"""
    python_exe = sys.executable
    main_script = PROJECT_ROOT / "main.py"

    content = f"""#!/bin/bash
# Taiwan Stock Daily Morning Routine
# delegate 給 morning-routine（Step 0~15+8b + Discord 摘要）
# Generated by taiwan-quant-project

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting morning-routine..."

cd "{PROJECT_ROOT}"

# 啟用虛擬環境（如存在）
if [ -f "venv/bin/activate" ]; then
    source venv/bin/activate
fi

# 執行完整早晨例行流程
"{python_exe}" "{main_script}" morning-routine --notify >> "{log_dir}/morning_routine.log" 2>&1

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Morning routine completed."
"""
    output.write_text(content, encoding="utf-8")
    output.chmod(output.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"  Shell 腳本: {output}")


def _generate_plist(output: Path, sh_path: Path) -> None:
    """產生每日 LaunchAgent plist。"""
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.taiwan-quant.daily-sync</string>
    <key>ProgramArguments</key>
    <array>
        <string>{sh_path}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>23</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{PROJECT_ROOT}/logs/launchd_daily.log</string>
    <key>StandardErrorPath</key>
    <string>{PROJECT_ROOT}/logs/launchd_daily_err.log</string>
    <key>WorkingDirectory</key>
    <string>{PROJECT_ROOT}</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
"""
    output.write_text(content, encoding="utf-8")
    print(f"  Plist: {output}")


def _generate_weekly_shell(output: Path, log_dir: Path) -> None:
    """產生每週四 sync-holding shell 腳本。"""
    python_exe = sys.executable
    main_script = PROJECT_ROOT / "main.py"

    content = f"""#!/bin/bash
# Taiwan Stock Weekly Holding Sync
# 每週四執行：同步大戶持股分級週資料
# Generated by taiwan-quant-project

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting weekly holding sync..."

cd "{PROJECT_ROOT}"

# 啟用虛擬環境（如存在）
if [ -f "venv/bin/activate" ]; then
    source venv/bin/activate
fi

# 同步大戶持股分級（最近 4 週）
"{python_exe}" "{main_script}" sync-holding >> "{log_dir}/weekly_holding.log" 2>&1

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Weekly holding sync completed."
"""
    output.write_text(content, encoding="utf-8")
    output.chmod(output.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"  週 Shell 腳本: {output}")


def _generate_weekly_plist(output: Path, sh_path: Path) -> None:
    """產生每週四 LaunchAgent plist。"""
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.taiwan-quant.weekly-holding</string>
    <key>ProgramArguments</key>
    <array>
        <string>{sh_path}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key>
        <integer>4</integer>
        <key>Hour</key>
        <integer>23</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{PROJECT_ROOT}/logs/launchd_weekly.log</string>
    <key>StandardErrorPath</key>
    <string>{PROJECT_ROOT}/logs/launchd_weekly_err.log</string>
    <key>WorkingDirectory</key>
    <string>{PROJECT_ROOT}</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
"""
    output.write_text(content, encoding="utf-8")
    print(f"  週 Plist: {output}")


def _print_instructions(sh_path: Path, plist_path: Path, log_dir: Path) -> None:
    """列印每日排程安裝說明。"""
    print(f"""
{"=" * 65}
macOS LaunchAgent 安裝說明（每日 morning-routine）
{"=" * 65}

【安裝】

  cp "{plist_path}" ~/Library/LaunchAgents/
  launchctl load ~/Library/LaunchAgents/com.taiwan-quant.daily-sync.plist

【驗證】

  launchctl list | grep taiwan-quant

【手動執行測試】

  launchctl start com.taiwan-quant.daily-sync

【移除】

  launchctl unload ~/Library/LaunchAgents/com.taiwan-quant.daily-sync.plist
  rm ~/Library/LaunchAgents/com.taiwan-quant.daily-sync.plist

排程時間：每日 23:00（morning-routine：Step 0~15+8b + Discord 摘要）
日誌位置：{log_dir}/morning_routine.log
{"=" * 65}
""")


def _print_weekly_instructions(sh_path: Path, plist_path: Path, log_dir: Path) -> None:
    """列印週排程安裝說明。"""
    print(f"""
{"=" * 65}
macOS LaunchAgent 安裝說明（每週四 sync-holding）
{"=" * 65}

【安裝】

  cp "{plist_path}" ~/Library/LaunchAgents/
  launchctl load ~/Library/LaunchAgents/com.taiwan-quant.weekly-holding.plist

【驗證】

  launchctl list | grep taiwan-quant

【手動執行測試】

  launchctl start com.taiwan-quant.weekly-holding

【移除】

  launchctl unload ~/Library/LaunchAgents/com.taiwan-quant.weekly-holding.plist
  rm ~/Library/LaunchAgents/com.taiwan-quant.weekly-holding.plist

排程時間：每週四 23:00（TWSE 大戶持股資料通常於週四更新）
日誌位置：{log_dir}/weekly_holding.log
{"=" * 65}
""")
