"""Windows Task Scheduler 任務產生器。"""

from __future__ import annotations

import sys
from pathlib import Path

from src.config import PROJECT_ROOT


def generate_scripts() -> tuple[Path, Path]:
    """產生每日 .bat 批次檔 + Task Scheduler XML，回傳 (bat_path, xml_path)。"""
    script_dir = PROJECT_ROOT / "scripts"
    script_dir.mkdir(exist_ok=True)
    log_dir = PROJECT_ROOT / "logs"
    log_dir.mkdir(exist_ok=True)

    batch_path = script_dir / "daily_sync.bat"
    xml_path = script_dir / "task_schedule.xml"

    _generate_batch(batch_path, log_dir)
    _generate_xml(xml_path, batch_path)
    _print_instructions(batch_path, xml_path, log_dir)

    return batch_path, xml_path


def generate_weekly_scripts() -> tuple[Path, Path]:
    """產生每週四 sync-holding .bat + Task Scheduler XML，回傳 (bat_path, xml_path)。"""
    script_dir = PROJECT_ROOT / "scripts"
    script_dir.mkdir(exist_ok=True)
    log_dir = PROJECT_ROOT / "logs"
    log_dir.mkdir(exist_ok=True)

    batch_path = script_dir / "weekly_sync.bat"
    xml_path = script_dir / "weekly_task_schedule.xml"

    _generate_weekly_batch(batch_path, log_dir)
    _generate_weekly_xml(xml_path, batch_path)
    _print_weekly_instructions(batch_path, xml_path, log_dir)

    return batch_path, xml_path


def _generate_batch(output: Path, log_dir: Path) -> None:
    """產生 .bat 批次檔。"""
    python_exe = sys.executable
    main_script = PROJECT_ROOT / "main.py"

    content = f"""@echo off
REM Taiwan Stock Auto-Sync Batch Script
REM Generated by taiwan-quant-project

echo [%date% %time%] Starting daily sync...

cd /d "{PROJECT_ROOT}"

if exist venv\\Scripts\\activate.bat (
    call venv\\Scripts\\activate.bat
)

REM Step 1: 同步日K + TAIEX
"{python_exe}" "{main_script}" sync >> "{log_dir}\\sync.log" 2>&1

REM Step 2: 同步借券賣出（全市場，前一交易日）
"{python_exe}" "{main_script}" sync-sbl >> "{log_dir}\\sync_sbl.log" 2>&1

REM Step 3: 同步分點進出（上次 discover 推薦標的）
"{python_exe}" "{main_script}" sync-broker --from-discover >> "{log_dir}\\sync_broker.log" 2>&1

REM Step 4: 重算技術指標
"{python_exe}" "{main_script}" compute >> "{log_dir}\\compute.log" 2>&1

REM Step 5: watchlist 多因子篩選
"{python_exe}" "{main_script}" scan --notify >> "{log_dir}\\scan.log" 2>&1

REM Step 6: 全市場掃描（SBL + 分點資料已就緒）
"{python_exe}" "{main_script}" discover --notify >> "{log_dir}\\discover.log" 2>&1

echo [%date% %time%] Daily sync completed.
"""
    output.write_text(content, encoding="utf-8")
    print(f"  批次檔: {output}")


def _generate_xml(output: Path, batch_path: Path) -> None:
    """產生 Task Scheduler XML 設定檔。"""
    content = f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Taiwan Stock Quantitative System - Daily Auto Sync</Description>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2026-02-17T23:00:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>
    <ExecutionTimeLimit>PT2H</ExecutionTimeLimit>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
  </Settings>
  <Actions>
    <Exec>
      <Command>{batch_path}</Command>
      <WorkingDirectory>{PROJECT_ROOT}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"""
    output.write_text(content, encoding="utf-16")
    print(f"  任務 XML: {output}")


def _generate_weekly_batch(output: Path, log_dir: Path) -> None:
    """產生每週四 sync-holding .bat 批次檔。"""
    python_exe = sys.executable
    main_script = PROJECT_ROOT / "main.py"

    content = f"""@echo off
REM Taiwan Stock Weekly Holding Sync
REM 每週四執行：同步大戶持股分級週資料（TWSE，FinMind TaiwanStockHoldingSharesPer）
REM Generated by taiwan-quant-project

echo [%date% %time%] Starting weekly holding sync...

cd /d "{PROJECT_ROOT}"

if exist venv\\Scripts\\activate.bat (
    call venv\\Scripts\\activate.bat
)

REM 同步大戶持股分級（最近 4 週）
"{python_exe}" "{main_script}" sync-holding >> "{log_dir}\\weekly_holding.log" 2>&1

echo [%date% %time%] Weekly holding sync completed.
"""
    output.write_text(content, encoding="utf-8")
    print(f"  週批次檔: {output}")


def _generate_weekly_xml(output: Path, batch_path: Path) -> None:
    """產生每週四 Task Scheduler XML 設定檔。"""
    content = f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Taiwan Stock Quantitative System - Weekly Holding Distribution Sync</Description>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2026-03-05T23:00:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByWeek>
        <WeeksInterval>1</WeeksInterval>
        <DaysOfWeek>
          <Thursday />
        </DaysOfWeek>
      </ScheduleByWeek>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>
    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
  </Settings>
  <Actions>
    <Exec>
      <Command>{batch_path}</Command>
      <WorkingDirectory>{PROJECT_ROOT}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"""
    output.write_text(content, encoding="utf-16")
    print(f"  週任務 XML: {output}")


def _print_weekly_instructions(batch_path: Path, xml_path: Path, log_dir: Path) -> None:
    """列印週排程安裝說明。"""
    print(f"""
{"=" * 65}
Windows 工作排程器安裝說明（每週四 sync-holding）
{"=" * 65}

【方法一：命令列匯入（建議）】

  以系統管理員開啟 cmd，執行：
  schtasks /create /tn "TaiwanStockWeeklyHolding" /xml "{xml_path}"

  驗證：
  schtasks /query /tn "TaiwanStockWeeklyHolding"

【方法二：GUI 匯入】

  開啟「工作排程器」(taskschd.msc) → 匯入工作 → 選擇 {xml_path}

【測試】

  schtasks /run /tn "TaiwanStockWeeklyHolding"

【移除】

  schtasks /delete /tn "TaiwanStockWeeklyHolding" /f

排程時間：每週四 23:00（TWSE 大戶持股資料通常於週四更新）
日誌位置：{log_dir}\\weekly_holding.log
{"=" * 65}
""")


def _print_instructions(batch_path: Path, xml_path: Path, log_dir: Path) -> None:
    """列印安裝說明。"""
    print(f"""
{"=" * 65}
Windows 工作排程器安裝說明
{"=" * 65}

【方法一：命令列匯入（建議）】

  以系統管理員開啟 cmd，執行：
  schtasks /create /tn "TaiwanStockAutoSync" /xml "{xml_path}"

  驗證：
  schtasks /query /tn "TaiwanStockAutoSync"

【方法二：GUI 匯入】

  開啟「工作排程器」(taskschd.msc) → 匯入工作 → 選擇 {xml_path}

【測試】

  schtasks /run /tn "TaiwanStockAutoSync"

【移除】

  schtasks /delete /tn "TaiwanStockAutoSync" /f

排程時間：每日 23:00
日誌位置：{log_dir}
{"=" * 65}
""")
